services:
  rtfs:
    image: ghcr.io/abstractumbra/rtfs:latest
    container_name: "rtfs"
    restart: "unless-stopped"
    volumes:
      - "./repos.json:/app/repos.json:rw"
    environment:
      API_KEY_FILE: /run/secrets/api_key
    ports:
      - 8030:8030
    secrets:
      - api_key

secrets:
  api_key:
    file: ./api_key
