services:
  rtfs:
    image: ghcr.io/abstractumbra/rtfs:latest
    container_name: "rtfs"
    restart: "unless-stopped"
    env_file:
      - .env
    networks:
      main:

networks:
  main:
    external:
      true
